# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinkBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, default=None, upload_to='profile/links/base/logo/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aim',
            field=models.CharField(max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, default=None, upload_to='profile/pic/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='profile/cv/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='link',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.LinkBase'),
        ),
    ]
