# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170523_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.Profile'),
        ),
    ]
