# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20161119_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Skill Category'),
        ),
    ]
