# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20161119_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ManyToManyField(to='members.Profile'),
        ),
    ]
