# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20161119_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aboutme',
            new_name='about',
        ),
    ]
