# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20161119_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default=None, upload_to='profile/cv/%Y/%m/%d'),
        ),
    ]
