# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20161119_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
