# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20161124_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='profiles',
            field=models.ManyToManyField(to='members.Profile'),
        ),
    ]
