# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20161124_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='certificate',
            field=models.FileField(blank=True, default=None, upload_to='profile/projects/certificates/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='members.Profile'),
        ),
    ]
