# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20161126_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('skill', 'skill_category')]),
        ),
    ]
