# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20161203_1310'),
        ('members', '0012_auto_20161126_2105'),
    ]

    operations = [
    ]
