# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to=products.models.upload_link)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('photo', models.ImageField(upload_to=products.models.scramble_uploaded_filename)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Menu'),
        ),
    ]
