# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170524_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='products/detail/compontents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='details',
        ),
        migrations.AlterField(
            model_name='link',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='products.Menu'),
        ),
        migrations.AddField(
            model_name='component',
            name='actions',
            field=models.ManyToManyField(to='products.Link'),
        ),
        migrations.AddField(
            model_name='component',
            name='detail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.Detail'),
        ),
        migrations.AddField(
            model_name='menu',
            name='detail',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Detail'),
        ),
    ]
