# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170524_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='actions',
            field=models.ManyToManyField(blank=True, null=True, to='products.Link'),
        ),
    ]
