# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_detail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='aligntype',
            field=models.CharField(choices=[('LR', 'Left To Right'), ('C', 'Center'), ('RL', 'Right to Left')], default='LR', max_length=1),
        ),
        migrations.AddField(
            model_name='component',
            name='background',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
