# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170601_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='aligntype',
            field=models.CharField(choices=[('LR', 'Left To Right'), ('C', 'Center'), ('RL', 'Right to Left')], default='LR', max_length=5),
        ),
    ]
