# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170601_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='background1',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
