# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170601_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='products.Menu'),
        ),
    ]
