# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20161119_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
